### ISSUE TITLE
[Refactor] 2차 코드리뷰 반영

### ISSUE THREAD

**Issue by j2h30728** [j2h30728/marvelous#3]
### 🤸 Describe the required feature
- [2차 코드리뷰](https://github.com/j2h30728/marvelous/issues/2)에 대한 2차 리팩토링

### 🏊 Todo
- [x] 식별자 네이밍 변경
    - [x]  isGoback => isRootPath  변경
    - [x] char => charactor 변경
    - [x] useGetDetail => useGetCharaterDetailData
- [x]  API URL 에 as const 적용
- [x] 공통 이미지 컴포넌트의 역할 바로잡기
- [x] 공통 컨테이너 컴포넌트 제거
- [x] useFetch 변경
- [x] 컴포넌트의 추상화단계 조정
